### ISSUE TITLE
View change log

### ISSUE THREAD

**Issue by kennyphan100** [JamesPartsafas/ConcordiaCurriculumManager#24]
As a logged-in user, I want to access and view the change log, so I can apply the modifications from the approved curriculum change request.

[Story Points: 15]
[Priority: Medium]
[Risk: Medium]

Tasks:
- [x] #289 
- [x] #364
- [x] #441  
- [x] #450 
- [x] #482 
- [x] #486  
- [x] #549 

Demo steps:
Given I’m a logged-in user
When I click on access changelog
Then I should be able to view a list of change from all the dossier

**Comment by rogersi9** [comment]
@zihao429 What are we still missing here?

**Comment by JamesPartsafas** [comment]
> @zihao429 What are we still missing here?

@rogersi9 I believe Zi Hao is currently working on adding an extra field to the DTO to also return course grouping data so we can display that. In addition, I'm also working on returning grouping data in the dossier report DTO so that can be displayed on the dossier report page. I'm not sure when Zi Hao will finish his part for the changelog, but I should be finished with my part later today, so we'll have groupings in the dossier report endpoint.
